#include "DepthoratorController.h"
#include "DepthoratorIDs.h"
#include "DepthoratorKnob.h"
#include "DepthoratorLogoView.h"
#include "base/source/fstreamer.h"
#include "vstgui/plugin-bindings/vst3editor.h"
#include "vstgui/lib/controls/coptionmenu.h"
#include "vstgui/lib/controls/ctextedit.h"
#include "vstgui/uidescription/uiattributes.h"
#include <algorithm>
#include <array>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <cstdlib>
#include <string>
#include <vector>
namespace Depthorator { using namespace Steinberg; using namespace Steinberg::Vst; namespace {
constexpr int32 kGuiZoomTag=9000;
void copyAscii(const std::string& text,String128 dest){std::size_t i=0;for(;i<text.size()&&i<127;++i)dest[i]=static_cast<TChar>(static_cast<unsigned char>(text[i]));dest[i]=0;}
std::string toAscii(const TChar* text){std::string r;if(!text)return r;for(std::size_t i=0;text[i]!=0&&i<127;++i){auto c=static_cast<unsigned int>(text[i]);if(c<128u)r.push_back(static_cast<char>(c));}return r;}
std::string trim(std::string s){auto f=s.find_first_not_of(" \t\r\n");if(f==std::string::npos)return{};auto l=s.find_last_not_of(" \t\r\n");return s.substr(f,l-f+1);}
bool parseNumber(const std::string& text,double& value){std::string t=trim(text);if(t.empty())return false;std::replace(t.begin(),t.end(),',','.');char* end=nullptr;value=std::strtod(t.c_str(),&end);return end!=t.c_str();}
std::string percentText(ParamValue v){char b[32]{};std::snprintf(b,sizeof(b),"%.0f %%",std::clamp(v,0.0,1.0)*100.0);return b;}
constexpr std::array<const char*,16> kSyncTimeNames{{"1/32","1/32 T","1/32 D","1/16","1/16 T","1/16 D","1/8","1/8 T","1/8 D","1/4","1/4 T","1/4 D","1/2","1/2 T","1/2 D","1/1"}};
}
tresult PLUGIN_API Controller::initialize(FUnknown* c){auto r=EditController::initialize(c);if(r!=kResultOk)return r;constexpr int32 f=ParameterInfo::kCanAutomate;parameters.addParameter(STR16("Time"),STR16(""),0,6.0/15.0,f,kTime);parameters.addParameter(STR16("Feedback"),STR16("%"),0,.42,f,kFeedback);parameters.addParameter(STR16("Depth"),STR16("%"),0,0.,f,kDepth);parameters.addParameter(STR16("Curve"),STR16("%"),0,.5,f,kCurve);parameters.addParameter(STR16("Size"),STR16("%"),0,.74,f,kSize);parameters.addParameter(STR16("Decay"),STR16("s"),0,.48,f,kDecay);parameters.addParameter(STR16("Damping"),STR16("%"),0,.55,f,kDamping);parameters.addParameter(STR16("Width"),STR16("%"),0,.75,f,kWidth);parameters.addParameter(STR16("Duck"),STR16("%"),0,.25,f,kDuck);parameters.addParameter(STR16("Mix"),STR16("%"),0,.35,f,kMix);parameters.addParameter(STR16("Sync"),STR16(""),1,1.,f,kSync);parameters.addParameter(STR16("Mode"),STR16(""),2,.5,f,kMode);return kResultOk;}
tresult PLUGIN_API Controller::setState(IBStream* s){if(!s)return kInvalidArgument;IBStreamer st(s,kLittleEndian);double z=1.;if(!st.readDouble(z))return kResultFalse;guiZoom_=z>=1.25?1.5:1.0;if(editor_)editor_->setZoomFactor(guiZoom_);return kResultOk;}
tresult PLUGIN_API Controller::getState(IBStream* s){if(!s)return kInvalidArgument;IBStreamer st(s,kLittleEndian);return st.writeDouble(guiZoom_)?kResultOk:kResultFalse;}
IPlugView* PLUGIN_API Controller::createView(FIDString n){if(n&&std::strcmp(n,ViewType::kEditor)==0){auto* e=new VSTGUI::VST3Editor(this,"view","Depthorator.uidesc");e->setAllowedZoomFactors(std::vector<double>{1.,1.5});e->setEditorSizeConstrains(VSTGUI::CPoint(1000.,500.),VSTGUI::CPoint(1000.,500.));editor_=e;e->setZoomFactor(guiZoom_);return e;}return nullptr;}
void Controller::updateTimeDisplayMode(){bool s=getParamNormalized(kSync)>=.5;auto v=static_cast<float>(getParamNormalized(kTime));if(timeEdit_){timeEdit_->setVisible(!s);timeEdit_->setValueNormalized(v);timeEdit_->invalid();}if(timeMenu_){timeMenu_->setVisible(s);timeMenu_->setValueNormalized(v);timeMenu_->invalid();}}
tresult PLUGIN_API Controller::setParamNormalized(Steinberg::Vst::ParamID t,ParamValue v){auto r=EditController::setParamNormalized(t,v);if(r==kResultOk&&t==kSync){updateTimeDisplayMode();if(auto* p=parameters.getParameter(kTime))p->changed();}return r;}
VSTGUI::CView* Controller::createCustomView(VSTGUI::UTF8StringPtr n,const VSTGUI::UIAttributes& a,const VSTGUI::IUIDescription*,VSTGUI::VST3Editor* e){if(!n||!e)return nullptr;VSTGUI::CPoint o{0.,0.},s{80.,80.};a.getPointAttribute("origin",o);a.getPointAttribute("size",s);VSTGUI::CRect r(o.x,o.y,o.x+s.x,o.y+s.y);if(std::strcmp(n,"DepthoratorBrandLogo")==0)return new DepthoratorLogoView(r);int32 t=-1;auto st=DepthoratorKnob::Style::Small;if(std::strcmp(n,"DepthKnobTime")==0)t=kTime;else if(std::strcmp(n,"DepthKnobFeedback")==0)t=kFeedback;else if(std::strcmp(n,"DepthKnobHero")==0){t=kDepth;st=DepthoratorKnob::Style::Hero;}else if(std::strcmp(n,"DepthKnobCurve")==0)t=kCurve;else if(std::strcmp(n,"DepthKnobSize")==0)t=kSize;else if(std::strcmp(n,"DepthKnobDecay")==0)t=kDecay;else if(std::strcmp(n,"DepthKnobDamping")==0)t=kDamping;else if(std::strcmp(n,"DepthKnobWidth")==0)t=kWidth;else if(std::strcmp(n,"DepthKnobDuck")==0)t=kDuck;else if(std::strcmp(n,"DepthKnobMix")==0)t=kMix;else return nullptr;return new DepthoratorKnob(r,e,t,st);}
VSTGUI::CView* Controller::verifyView(VSTGUI::CView* v,const VSTGUI::UIAttributes&,const VSTGUI::IUIDescription*,VSTGUI::VST3Editor* e){if(auto* c=dynamic_cast<VSTGUI::CControl*>(v)){if(c->getTag()==kGuiZoomTag){editor_=e;c->setListener(this);c->setMin(0.f);c->setMax(1.f);c->setValueNormalized(guiZoom_>=1.25?1.f:0.f);return v;}}if(auto* x=dynamic_cast<VSTGUI::CTextEdit*>(v)){if(x->getTag()==static_cast<int32>(kTime)){timeEdit_=x;updateTimeDisplayMode();return v;}}if(auto* m=dynamic_cast<VSTGUI::COptionMenu*>(v)){if(m->getTag()==static_cast<int32>(kTime)){timeMenu_=m;m->removeAllEntry();for(auto* n:kSyncTimeNames)m->addEntry(n);m->setMin(0.f);m->setMax(15.f);updateTimeDisplayMode();return v;}}return v;}
void Controller::valueChanged(VSTGUI::CControl* c){if(!c||c->getTag()!=kGuiZoomTag||!editor_)return;guiZoom_=c->getValueNormalized()>=.5f?1.5:1.0;editor_->setZoomFactor(guiZoom_);}
void Controller::willClose(VSTGUI::VST3Editor* editor){if(editor_==editor)editor_=nullptr;timeMenu_=nullptr;timeEdit_=nullptr;}
tresult PLUGIN_API Controller::getParamStringByValue(Steinberg::Vst::ParamID id,ParamValue v,String128 s){v=std::clamp(v,0.,1.);std::string t;switch(id){case kTime:if(getParamNormalized(kSync)>=.5){int i=std::clamp(static_cast<int>(std::round(v*15.)),0,15);t=kSyncTimeNames[static_cast<std::size_t>(i)];}else{double ms=20.+v*1980.;char b[32]{};std::snprintf(b,sizeof(b),ms<100.?"%.1f ms":"%.0f ms",ms);t=b;}break;case kDecay:{double sec=.30+v*v*11.70;char b[32]{};std::snprintf(b,sizeof(b),"%.1f s",sec);t=b;break;}case kSync:t=v>=.5?"SYNC":"FREE";break;case kMode:{int m=std::clamp(static_cast<int>(std::round(v*2.)),0,2);t=m==0?"MONO":(m==1?"STEREO":"PING-PONG");break;}case kFeedback:case kDepth:case kCurve:case kSize:case kDamping:case kWidth:case kDuck:case kMix:t=percentText(v);break;default:return EditController::getParamStringByValue(id,v,s);}copyAscii(t,s);return kResultTrue;}
tresult PLUGIN_API Controller::getParamValueByString(Steinberg::Vst::ParamID id,TChar* s,ParamValue& v){std::string t=trim(toAscii(s));if(t.empty())return kResultFalse;if(id==kTime){if(getParamNormalized(kSync)>=.5){for(int i=0;i<16;++i)if(t==kSyncTimeNames[static_cast<std::size_t>(i)]){v=static_cast<double>(i)/15.;return kResultTrue;}return kResultFalse;}double ms=0.;if(!parseNumber(t,ms))return kResultFalse;v=std::clamp((ms-20.)/1980.,0.,1.);return kResultTrue;}if(id==kDecay){double sec=0.;if(!parseNumber(t,sec))return kResultFalse;sec=std::clamp(sec,.30,12.);v=std::sqrt((sec-.30)/11.70);v=std::clamp(v,0.,1.);return kResultTrue;}switch(id){case kFeedback:case kDepth:case kCurve:case kSize:case kDamping:case kWidth:case kDuck:case kMix:{double p=0.;if(!parseNumber(t,p))return kResultFalse;v=std::clamp(p/100.,0.,1.);return kResultTrue;}case kSync:if(t=="SYNC"||t=="sync"){v=1.;return kResultTrue;}if(t=="FREE"||t=="free"){v=0.;return kResultTrue;}return kResultFalse;case kMode:if(t=="MONO"||t=="mono"){v=0.;return kResultTrue;}if(t=="STEREO"||t=="stereo"){v=.5;return kResultTrue;}if(t=="PING-PONG"||t=="ping-pong"||t=="PING PONG"||t=="ping pong"){v=1.;return kResultTrue;}return kResultFalse;default:return EditController::getParamValueByString(id,s,v);}}
tresult PLUGIN_API Controller::setComponentState(IBStream* s){if(!s)return kInvalidArgument;IBStreamer st(s,kLittleEndian);const std::array<Steinberg::Vst::ParamID,12> ids{{kTime,kFeedback,kDepth,kCurve,kSize,kDecay,kDamping,kWidth,kDuck,kMix,kSync,kMode}};for(auto id:ids){double v=0.;if(!st.readDouble(v))return kResultFalse;setParamNormalized(id,v);}return kResultOk;}
} // namespace Depthorator
